# Generated by Django 4.2.7 on 2023-12-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
